version: '3.7'
services:
  db:
   image: mysql:5.7
   env_file:
     - .env
   environment:
     - MYSQL_ROOT_PASSWORD=$DATABASE_PASSWORD
   ports:
     - 3306:3306
   volumes:
     - ./db/mysql/volumes:/var/lib/mysql
  web:
    build: 
      context: .
      dockerfile: docker/web/Dockerfile 
    command: npm run dev
    volumes:
      - ./web:/app
    ports:
      - 8080:3000 
  backend:
    build: 
      context: .
      dockerfile: docker/backend/Dockerfile
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - "bundle:/usr/local/bundle"
    env_file:
      - .env
    command: >
      sh -c "
        rm -f tmp/pids/server.pid &&
        bundle install --quiet &&
        bin/rails server -b 0.0.0.0"
    ports:
      - 3000:3000
    tty: true
    stdin_open: true

volumes:
  bundle:
